### PR TITLE
Extension GUI update

### PR DESCRIPTION
**Pull request by Mast3rwaf1z**
# Fixing branch issues
There were issues between issue #22 and issue #25 where the code was restructured in #25 to such an extend that it broke #22. i have fixed these issues and implemented all the features in #25 into the GUI from #22 and updated the page with all the controls

I have also added more buttons to the bottom of the window to reflect these changes

This pull request should also close both of these issues, as the branch is a merge of the two branches for each issue

### CODE REVIEW

**Comment by Mast3rwaf1z** [comment]
Please refer to #30 as this branch had issues merging with #25

**Comment by Mast3rwaf1z** [comment]
converted to draft until i have fixed the stepping issue in #29

**Comment by Mast3rwaf1z** [comment]
fixed the issue in #29, please review this pull request rather than that one and merge it instead of #29  and #27

**Comment by michelealbano** [comment]
redundant with 26

**Pull request merged**
